id = "bookmark"
name = "Bookmark"
description = "Bookmark"
version = "0.1.0"
schema_version = 1
authors = ["A23187 <a23187.1979421048@gmail.com>"]
repository = "https://github.com/A-23187/zed-bookmark"

[language_servers.bookmark-language-server]
name = "Bookmark Language Server"
languages = ["Plain Text"]
